### ISSUE TITLE
Wrong UI state when loading a script with errors

### ISSUE THREAD

**Issue by rzumer** [Jamiras/RATools#11]
As of version 1.3.1, when the application first launches, the main view is empty and some menu items are disabled.

When a script is selected for compilation, all parsed entries are displayed in a detail view and menu items (Refresh Current / Update Local) are enabled.

However, when a script cannot be parsed due to an error, the UI is still set to a loaded state. An empty detail view is displayed, and menu items are enabled erroneously.

Selecting "Update Local" in this state leads to an unhandled exception (in this case, due to a missing identifier):
```
09:52:14.852 ERR Unhandled exception: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.OfType[TResult](IEnumerable source)
   at RATools.ViewModels.UpdateLocalViewModel..ctor(GameViewModel game)
   at RATools.ViewModels.MainWindowViewModel.UpdateLocal()
   at Jamiras.Commands.DelegateCommand.Execute()
   at Jamiras.Commands.CommandBase.System.Windows.Input.ICommand.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Boolean isSingleParameter)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Boolean isSingleParameter, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.WrappedInvoke(Delegate callback, Object args, Boolean isSingleParameter, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.runTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Boolean isSingleParameter)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Boolean isSingleParameter, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.WrappedInvoke(Delegate callback, Object args, Boolean isSingleParameter, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Boolean isSingleParameter)
   at System.Windows.Threading.Dispatcher.Invoke(DispatcherPriority priority, Delegate method, Object arg)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at RATools.App.Main()
```

When loading a script fails due to a missing notes file, an error message is displayed when selecting "Update Local" instead, and the UI remains in a loaded state, so the behaviors should be consistent regardless of the chosen solution.

**Comment by Jamiras** [comment]
When a parse error occurs, the script is intentionally left partially loaded so you can Refresh/F5 to recompile it. However, as you've identified, the Update Local window can't handle things in this state.

I've updated the Update Local command to remain disabled if no achievements were generated. This includes cases where the script only generates RichPresence and/or Leaderboards.
